export const sample_foods = [
  {
    id: '1',
    name: 'Butter Chicken',
    cookTime: '45-60',
    price: 15,
    favorite: true,
    origins: ['India', 'Punjab'],
    stars: 4.8,
    imageUrl: 'food-1.jpg',
    tags: ['MainCourse', 'Chicken', 'Dinner'],
  },
  {
    id: '2',
    name: 'Paneer Tikka',
    price: 12,
    cookTime: '30-40',
    favorite: false,
    origins: ['India', 'North India'],
    stars: 4.5,
    imageUrl: 'food-2.jpg',
    tags: ['Appetizer', 'Vegetarian', 'Tandoor'],
  },
  {
    id: '3',
    name: 'Masala Dosa',
    price: 8,
    cookTime: '20-30',
    favorite: true,
    origins: ['India', 'South India'],
    stars: 4.7,
    imageUrl: 'food-3.jpg',
    tags: ['Breakfast', 'Vegetarian', 'SouthIndian'],
  },
  {
    id: '4',
    name: 'Rogan Josh',
    price: 18,
    cookTime: '60-80',
    favorite: false,
    origins: ['India', 'Kashmir'],
    stars: 4.6,
    imageUrl: 'food-4.jpg',
    tags: ['MainCourse', 'Lamb', 'Dinner'],
  },
  {
    id: '5',
    name: 'Chole Bhature',
    price: 10,
    cookTime: '30-40',
    favorite: true,
    origins: ['India', 'Punjab'],
    stars: 4.4,
    imageUrl: 'food-5.jpg',
    tags: ['Breakfast', 'Vegetarian', 'Punjabi'],
  },
  {
    id: '6',
    name: 'Biryani',
    price: 14,
    cookTime: '50-70',
    favorite: false,
    origins: ['India', 'Hyderabad'],
    stars: 4.9,
    imageUrl: 'food-6.jpg',
    tags: ['MainCourse', 'Rice', 'Dinner'],
  },
];

export const sample_tags = [
  { name: 'All', count: 6 },
  { name: 'MainCourse', count: 3 },
  { name: 'Vegetarian', count: 3 },
  { name: 'Breakfast', count: 2 },
  { name: 'Chicken', count: 1 },
  { name: 'Lamb', count: 1 },
  { name: 'Tandoor', count: 1 },
  { name: 'Rice', count: 1 },
  { name: 'SouthIndian', count: 1 },
  { name: 'Punjabi', count: 2 },
  { name: 'Dinner', count: 3 },
];

  
  export const sample_users = [
    {
      id: 1,
      name: 'Aravind Sasidharan',
      email: 'aravind@gmail.com',
      password: '12345',
      address: 'Trivandrum',
      isAdmin: false,
    },
    {
      id: 2,
      name: 'Ajith Sasidharan',
      email: 'ajith@gmail.com',
      password: '12345',
      address: 'Kollam',
      isAdmin: true,
    },
  ];